package com.synapse.social.studioasinc.shared.core.config

actual object SynapseConfig {
    actual val SUPABASE_URL: String = System.getenv("SUPABASE_URL") ?: ""
    actual val SUPABASE_ANON_KEY: String = System.getenv("SUPABASE_ANON_KEY") ?: ""
    actual val SUPABASE_SYNAPSE_S3_ENDPOINT_URL: String = System.getenv("SUPABASE_SYNAPSE_S3_ENDPOINT_URL") ?: ""
    actual val SUPABASE_SYNAPSE_S3_ENDPOINT_REGION: String = System.getenv("SUPABASE_SYNAPSE_S3_ENDPOINT_REGION") ?: ""
    actual val SUPABASE_SYNAPSE_S3_ACCESS_KEY_ID: String = System.getenv("SUPABASE_SYNAPSE_S3_ACCESS_KEY_ID") ?: ""
    actual val SUPABASE_SYNAPSE_S3_ACCESS_KEY: String = System.getenv("SUPABASE_SYNAPSE_S3_ACCESS_KEY") ?: ""
    actual val IMGBB_API_KEY: String = System.getenv("IMGBB_API_KEY") ?: ""
    actual val CLOUDINARY_CLOUD_NAME: String = System.getenv("CLOUDINARY_CLOUD_NAME") ?: ""
    actual val CLOUDINARY_API_KEY: String = System.getenv("CLOUDINARY_API_KEY") ?: ""
    actual val CLOUDINARY_API_SECRET: String = System.getenv("CLOUDINARY_API_SECRET") ?: ""
    actual val GEMINI_API_KEY: String = System.getenv("GEMINI_API_KEY") ?: ""

    actual val OPENAI_API_ENDPOINT: String = System.getenv("OPENAI_API_ENDPOINT") ?: "https://api.openai.com/v1/chat/completions"
    actual val ANTHROPIC_API_ENDPOINT: String = System.getenv("ANTHROPIC_API_ENDPOINT") ?: "https://api.anthropic.com/v1/messages"
    actual val OPENROUTER_API_ENDPOINT: String = System.getenv("OPENROUTER_API_ENDPOINT") ?: "https://openrouter.ai/api/v1/chat/completions"
    actual val GEMINI_API_ENDPOINT: String = System.getenv("GEMINI_API_ENDPOINT") ?: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
    actual val IMGBB_API_ENDPOINT: String = System.getenv("IMGBB_API_ENDPOINT") ?: "https://api.imgbb.com/1/upload"
    actual val CLOUDINARY_API_BASE_URL: String = System.getenv("CLOUDINARY_API_BASE_URL") ?: "https://api.cloudinary.com/v1_1/"
    actual val APP_WEBSITE_URL: String = System.getenv("APP_WEBSITE_URL") ?: "https://synapsesocial.vercel.app"
    actual val GITHUB_BUG_REPORT_URL: String = System.getenv("GITHUB_BUG_REPORT_URL") ?: "https://github.com/synapseSRC/synapseApp/issues/new?template=bug_report.md"
    actual val DEFAULT_QUIET_HOURS_START: String = System.getenv("DEFAULT_QUIET_HOURS_START") ?: "22:00"
    actual val DEFAULT_QUIET_HOURS_END: String = System.getenv("DEFAULT_QUIET_HOURS_END") ?: "08:00"
    actual val SUPABASE_REDIRECT_URL: String = System.getenv("SUPABASE_REDIRECT_URL") ?: "https://synapseofficial.vercel.app/"
    actual val X_BASE_URL: String = System.getenv("X_BASE_URL") ?: "https://x.com/"
    actual val INSTAGRAM_BASE_URL: String = System.getenv("INSTAGRAM_BASE_URL") ?: "https://instagram.com/"
    actual val FACEBOOK_BASE_URL: String = System.getenv("FACEBOOK_BASE_URL") ?: "https://facebook.com/"
    actual val LINKEDIN_BASE_URL: String = System.getenv("LINKEDIN_BASE_URL") ?: "https://linkedin.com/in/"
    actual val GITHUB_BASE_URL: String = System.getenv("GITHUB_BASE_URL") ?: "https://github.com/"
    actual val YOUTUBE_BASE_URL: String = System.getenv("YOUTUBE_BASE_URL") ?: "https://youtube.com/@"
}
