package com.synapse.social.studioasinc.shared.core.config

actual object SynapseConfig {
    actual val SUPABASE_URL: String = ""
    actual val SUPABASE_ANON_KEY: String = ""
    actual val SUPABASE_SYNAPSE_S3_ENDPOINT_URL: String = ""
    actual val SUPABASE_SYNAPSE_S3_ENDPOINT_REGION: String = ""
    actual val SUPABASE_SYNAPSE_S3_ACCESS_KEY_ID: String = ""
    actual val SUPABASE_SYNAPSE_S3_ACCESS_KEY: String = ""
    actual val IMGBB_API_KEY: String = ""
    actual val CLOUDINARY_CLOUD_NAME: String = ""
    actual val CLOUDINARY_API_KEY: String = ""
    actual val CLOUDINARY_API_SECRET: String = ""
    actual val GEMINI_API_KEY: String = ""

    actual val OPENAI_API_ENDPOINT: String = "https://api.openai.com/v1/chat/completions"
    actual val ANTHROPIC_API_ENDPOINT: String = "https://api.anthropic.com/v1/messages"
    actual val OPENROUTER_API_ENDPOINT: String = "https://openrouter.ai/api/v1/chat/completions"
    actual val GEMINI_API_ENDPOINT: String = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
    actual val IMGBB_API_ENDPOINT: String = "https://api.imgbb.com/1/upload"
    actual val CLOUDINARY_API_BASE_URL: String = "https://api.cloudinary.com/v1_1/"
    actual val APP_WEBSITE_URL: String = "https://synapsesocial.vercel.app"
    actual val GITHUB_BUG_REPORT_URL: String = "https://github.com/synapseSRC/synapseApp/issues/new?template=bug_report.md"
    actual val DEFAULT_QUIET_HOURS_START: String = "22:00"
    actual val DEFAULT_QUIET_HOURS_END: String = "08:00"
    actual val SUPABASE_REDIRECT_URL: String = "https://synapseofficial.vercel.app/"
    actual val X_BASE_URL: String = "https://x.com/"
    actual val INSTAGRAM_BASE_URL: String = "https://instagram.com/"
    actual val FACEBOOK_BASE_URL: String = "https://facebook.com/"
    actual val LINKEDIN_BASE_URL: String = "https://linkedin.com/in/"
    actual val GITHUB_BASE_URL: String = "https://github.com/"
    actual val YOUTUBE_BASE_URL: String = "https://youtube.com/@"
}
