import Foundation
import shared

/// A generic wrapper to collect Kotlin Coroutine Flows from iOS.
/// Note: Depending on KMP setup (e.g. SKIE or KMP-NativeCoroutines),
/// you might not need a manual wrapper, but this gives a fallback using the common
/// Swift-compatible interface generated by Kotlin (like `collect(collector: ...)`).
class FlowCollector<T>: shared.Kotlinx_coroutines_coreFlowCollector {
    private let callback: (T) -> Void

    init(callback: @escaping (T) -> Void) {
        self.callback = callback
    }

    func emit(value: Any?, completionHandler: @escaping (Error?) -> Void) {
        if let val = value as? T {
            callback(val)
        }
        completionHandler(nil)
    }
}

extension shared.Kotlinx_coroutines_coreFlow {
    /// Helper to bridge Kotlin Flow to Swift AsyncThrowingStream
    func asAsyncStream<T>(type: T.Type = T.self) -> AsyncThrowingStream<T, Error> {
        return AsyncThrowingStream { continuation in
            let collector = FlowCollector<T> { value in
                continuation.yield(value)
            }
            // Launch a task to collect
            Task {
                do {
                    try await self.collect(collector: collector)
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }
}
